### ISSUE TITLE
To change folders sort order

### ISSUE THREAD

**Issue by scomnoob** [mihnea-radulescu/imagefanreloaded#11]
Hello
Is it possible to add  ability to sort folders via 

1. Date Modified
2. Date Created

?

Many thanks

Even without it i almost stoped using xnview..

**Comment by mihnea-radulescu** [comment]
Hi @scomnoob,

Thank you for the feature suggestion!

Sure, I am going to implement it. I will let you know when the feature is done.

**Comment by mihnea-radulescu** [comment]
Hi again @scomnoob,

I have implemented the feature in [Release 2024-09-22](https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.09.22).

The keyboard keys N, C and M are now used for changing folder ordering between name ascending, creation time descending and last modification time descending.

**Comment by scomnoob** [comment]
many thanks!
