### ISSUE TITLE
Theoretical question (i am not a dev..

### ISSUE THREAD

**Issue by scomnoob** [mihnea-radulescu/imagefanreloaded#12]
Hello 

Many thanks for yo app

Little idea - is it real to compile it with latest Native AOT ?  Maybe it will be faster on my thousands of images :)

**Comment by mihnea-radulescu** [comment]
Hi @scomnoob,

I remember adding the Native AOT compilation flag at one point in time, and encountering multiple errors.

However, I don't think enabling it would bring a significant performance gain, as I already use the **PublishReadyToRun** flag in the compilation process. Native code generation does not appear to be a performance bottleneck for this kind of an application.

Best regards,
Mihnea
