### ISSUE TITLE
About the package name

### ISSUE THREAD

**Issue by zxp19821005** [mihnea-radulescu/imagefanreloaded#2]
As titled.
The package name in AUR is `imagefanreloaded-avalonia-bin` now.(https://aur.archlinux.org/packages/imagefanreloaded-avalonia-bin).
And I notice that the latest package's name has changed to `imagefanreloaded`.Do I need to change the package name?

**Comment by mihnea-radulescu** [comment]
Hi @zxp19821005,

Thank you for your inquiry!

The AUR package name does not need to be changed, it can stay as _imagefanreloaded-avalonia-bin_.

Additionally, all of the .NET dependencies in the AUR package can safely be removed, as .NET is now packaged in the application executable itself.

Best regards,
Mihnea

**Comment by zxp19821005** [comment]
All right,Thanks!
