### ISSUE TITLE
CLI support?

### ISSUE THREAD

**Issue by tifDev** [mihnea-radulescu/imagefanreloaded#3]
Hi,

Any option to run via cli? example: `imagefanreloaded /photos/my_image.png`

Thanks!

**Comment by mihnea-radulescu** [comment]
Thank you very much for your suggestion, @tifDev!

I will implement this feature with the next release.

**Comment by mihnea-radulescu** [comment]
Hi @tifDev,

I have added CLI support for both folders and files, and have created a new release featuring the changes.

As the requested feature is now part of the product, I am now closing this issue.

**Comment by tifDev** [comment]
Ok Will check, thanks!
