### ISSUE TITLE
XOpenDisplay failed error with Flatpak

### ISSUE THREAD

**Issue by andersrh** [mihnea-radulescu/imagefanreloaded#4]
I have tried to install the Flatpak, which is available on Flathub, but I get the following error, when I'm running the application:

`flatpak run io.github.mihnea_radulescu.imagefanreloaded
Unhandled exception. System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions)
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action``1 )
   at ImageFanReloaded.Program.Main(String[]) in /home/mihnea/Repositories/ImageFanReloaded/ImageFanReloaded/Program.cs:line 10`

I'm running Fedora 39 (Kinoite) with KDE Plasma 5.27.11 on Wayland.

**Comment by mihnea-radulescu** [comment]
Hi @andersrh,

Thank you for raising this issue!

Could you please check if the default (non-flatpak) version of the application produces the same error on your system: [https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.05.05](https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.05.05)?

**Comment by andersrh** [comment]
Hi @mihnea-radulescu 

Yes it works, when I run it on my system as non-flatpak (tested in a Fedora 39 container).

**Comment by andersrh** [comment]
Hi again @mihnea-radulescu 

I saw that an update just came out for the application on Flathub. After installing the update I can now open the application.

**Comment by andersrh** [comment]
but I must say that the application doesn't work that well on a 4K display with scaling enabled. It seems like it doesn't apply the scaling set in KDE's settings.

In the screenshot below, you can see how it looks like:

![Screenshot_20240510_081019](https://github.com/mihnea-radulescu/imagefanreloaded/assets/20405991/3f8e9a6d-a86b-4a02-a0dc-6121dfbc6776)

**Comment by andersrh** [comment]
but I must say that the application doesn't work that well on a 4K display with scaling enabled. It seems like it doesn't apply the scaling set in KDE's settings.

In the screenshot below, you can see how it looks like:

![Screenshot_20240510_081319](https://github.com/mihnea-radulescu/imagefanreloaded/assets/20405991/577f09d7-8366-4349-a8a1-d8df929b18db)

**Comment by mihnea-radulescu** [comment]
Hi @andersrh,

Thank you for the update!

I have published a revised version of the application on:
* GitHub - [https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.05.10](https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.05.10)
* Flathub - [https://flathub.org/apps/io.github.mihnea_radulescu.imagefanreloaded](https://flathub.org/apps/io.github.mihnea_radulescu.imagefanreloaded)

Please let me know if the Flatpak version of the app can now properly execute on your system.

Regarding the scaling, as the application is based on .NET 8 and the Avalonia UI framework, it is mostly agnostic of the desktop environment settings, beyond getting the dark vs light theme setting. I will create an issue on the [Avalonia UI GitHub](https://github.com/AvaloniaUI/Avalonia), maybe there are future plans for better integration with the DE.

**Comment by andersrh** [comment]
Hi. It worked with the new version. closing this issue. thanks a lot for your quick response :-)
