### ISSUE TITLE
need to press R on any folder...

### ISSUE THREAD

**Issue by scomnoob** [mihnea-radulescu/imagefanreloaded#6]
...to view subs
anyway to enable it forever with mark?

any way --- many thanks!!!!!!!!!!!!!!!!!!!!!

**Comment by mihnea-radulescu** [comment]
Hi @scomnoob,

Thank you for your feature request!

I have implemented it by enabling a **persistent recursive** folder access mode, using the key combo **Shift-R**.

Please check the latest release here: [https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.07.02](https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.07.02).
