### ISSUE TITLE
use up/down to view next folder in treeview

### ISSUE THREAD

**Issue by scomnoob** [mihnea-radulescu/imagefanreloaded#8]
use up/down to view next folder in treeview

now its not workings

thanks

**Comment by mihnea-radulescu** [comment]
Hi @scomnoob,

Thank you for the feedback!

The keys W-A-S-D, Up-Down-Left-Right, Backspace-Space and PageUp-PageDown are used for back and forward navigation through thumbnails and opened images in the thumbnails panel, thus they cannot be mapped to the folder TreeView control at the same time.

**Comment by scomnoob** [comment]
looks like epic fail:)

**Comment by mihnea-radulescu** [comment]
Hi @scomnoob,

I have fixed the arrow keys navigation in the folder tree view.

Here is the new release: [https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.07.13](https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.07.13).

Let me know if it now works as expected.

**Comment by scomnoob** [comment]
> Hi @scomnoob,
> 
> I have fixed the arrow keys navigation in the folder tree view.
> 
> Here is the new release: https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.07.13.
> 
> Let me know if it now works as expected.

works! many thanks!!!!!!!!!!!
