### ISSUE TITLE
feature req - copy path as text / open in explorer

### ISSUE THREAD

**Issue by scomnoob** [mihnea-radulescu/imagefanreloaded#9]
as i see i cant copy folder/photo path?

also Open in explorer - basic feature in image apps)))

thank you  a lot- i`m not using xnview now but your app :)

**Comment by mihnea-radulescu** [comment]
Hi @scomnoob,

Thank you for your suggestion!

I have updated the application accordingly: [https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.07.14](https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.07.14).

Let me know if it works as expected.
